create database if not exists data_service default character set utf8mb4 collate utf8mb4_unicode_ci;
use data_service;

DROP TABLE IF EXISTS job_sync_offset;
CREATE TABLE `job_sync_offset`
(
    `id`           bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `method`       varchar(64)         NOT NULL COMMENT '接口名称',
    `start_time`   datetime            NOT NULL COMMENT '修改起始时间',
    `end_time`     datetime            NOT NULL COMMENT '修改结束时间',
    `creator`      varchar(32)         NOT NULL DEFAULT 'system' COMMENT '创建人',
    `modifier`     varchar(32)         NOT NULL DEFAULT 'system' COMMENT '修改人',
    `is_deleted`   tinyint(4)          NOT NULL DEFAULT '0' COMMENT '删除标识。0: 未删除, 1: 已删除',
    `gmt_create`   datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `gmt_modified` datetime            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_method` (`method`)
) ENGINE = InnoDB COMMENT ='同步进度位点';

DROP TABLE IF EXISTS jst_order;
CREATE TABLE `jst_order`
(
    `id`                 bigint(20)  NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `is_cod`             varchar(8)           DEFAULT NULL COMMENT '是否货到付款',
    `l_id`               varchar(256)         DEFAULT NULL COMMENT '快递单号',
    `send_date`          datetime             DEFAULT NULL COMMENT '发货日期',
    `pay_date`           datetime             DEFAULT NULL COMMENT '支付时间',
    `freight`            varchar(64)          DEFAULT NULL COMMENT '运费，保留两位小数，单位（元）',
    `receiver_address`   text COMMENT '收货地址',
    `receiver_district`  varchar(64)          DEFAULT NULL COMMENT '区',
    `wms_co_id`          varchar(64)          DEFAULT NULL COMMENT '发货仓编号',
    `logistics_company`  varchar(64)          DEFAULT NULL COMMENT '快递公司',
    `free_amount`        varchar(64)          DEFAULT NULL COMMENT '抵扣金额',
    `shop_name`          varchar(64)          DEFAULT NULL COMMENT '店铺名称',
    `question_type`      varchar(64)          DEFAULT NULL COMMENT '问题类型，仅当问题订单时有效',
    `outer_pay_id`       varchar(128)         DEFAULT NULL COMMENT '外部支付单号',
    `so_id`              varchar(64)          DEFAULT NULL COMMENT '线上订单号，最长不超过 20;唯一',
    `type`               varchar(64)          DEFAULT NULL COMMENT '订单类型',
    `order_from`         varchar(64)          DEFAULT NULL COMMENT '订单来源',
    `status`             varchar(64)          DEFAULT NULL COMMENT '待付款：WaitPay；发货中：Delivering；被合并：Merged；异常：Question；被拆分：Split；等供销商|外仓发货：WaitOuterSent；已付款待审核：WaitConfirm；已客审待财审：WaitFConfirm；已发货：Sent；取消：Cancelled',
    `pay_amount`         varchar(64)          DEFAULT NULL COMMENT '应付金额，保留两位小数，单位（元）',
    `shop_buyer_id`      text COMMENT '买家昵称',
    `shop_status`        varchar(64)          DEFAULT NULL COMMENT '平台订单状态',
    `receiver_mobile`    text COMMENT '手机',
    `order_date`         datetime             DEFAULT NULL COMMENT '下单时间',
    `question_desc`      varchar(64)          DEFAULT NULL COMMENT '问题描述',
    `receiver_city`      varchar(64)          DEFAULT NULL COMMENT '收件信息-市',
    `receiver_state`     varchar(64)          DEFAULT NULL COMMENT '收件信息-省',
    `receiver_name`      varchar(512)         DEFAULT NULL COMMENT '收件信息-收件人',
    `o_id`               bigint(20)  NOT NULL COMMENT 'ERP 内部订单号，唯一',
    `shop_id`            bigint(20)           DEFAULT NULL COMMENT '店铺编号',
    `co_id`              bigint(20)           DEFAULT NULL COMMENT '公司编号',
    `pays`               text COMMENT '支付信息',
    `items`              mediumtext COMMENT '购买商品列表',
    `remark`             text COMMENT '订单备注；卖家备注',
    `drp_co_id_from`     varchar(64)          DEFAULT NULL COMMENT '分销商编号',
    `modified`           datetime             DEFAULT NULL COMMENT '修改时间',
    `labels`             varchar(256)         DEFAULT NULL COMMENT '多标签',
    `paid_amount`        varchar(64)          DEFAULT NULL COMMENT '实际支付金额',
    `currency`           varchar(64)          DEFAULT NULL COMMENT '币种',
    `buyer_message`      text COMMENT '买家留言',
    `lc_id`              varchar(64)          DEFAULT NULL COMMENT '物流公司编码',
    `invoice_title`      varchar(128)         DEFAULT NULL COMMENT '发票抬头',
    `invoice_type`       varchar(64)          DEFAULT NULL COMMENT '发票类型',
    `buyer_tax_no`       varchar(64)          DEFAULT NULL COMMENT '发票税号',
    `creator_name`       varchar(64)          DEFAULT NULL COMMENT '业务员',
    `plan_delivery_date` datetime             DEFAULT NULL COMMENT '计划发货时间',
    `node`               text COMMENT '线下备注',
    `receiver_town`      varchar(256)         DEFAULT NULL COMMENT '收件信息-街道',
    `drp_co_id_to`       varchar(256)         DEFAULT NULL COMMENT '供销商编号',
    `f_freight`          varchar(16)          DEFAULT NULL COMMENT '运费成本',
    `shop_site`          varchar(256)         DEFAULT NULL COMMENT '店铺站点信息',
    `un_lid`             varchar(128)         DEFAULT NULL COMMENT '国际物流单号',
    `end_time`           datetime             DEFAULT NULL COMMENT '收货时间（仅限头条放心购、京东、拼多多）',
    `receiver_country`   varchar(32)          DEFAULT NULL COMMENT '国家代码',
    `receiver_zip`       varchar(32)          DEFAULT NULL COMMENT '邮编',
    `seller_flag`        int(11)              DEFAULT NULL COMMENT '旗帜(1红旗，2黄旗，3绿旗，4蓝旗，5紫旗)）',
    `modified_begin`     datetime    NOT NULL COMMENT '修改起始时间',
    `modified_end`       datetime    NOT NULL COMMENT '修改结束时间',
    `page_index`         int(11)     NOT NULL COMMENT '页码',
    `page_size`          int(11)     NOT NULL COMMENT '页数',
    `creator`            varchar(32) NOT NULL COMMENT '创建人',
    `modifier`           varchar(32) NOT NULL COMMENT '修改人',
    `is_deleted`         tinyint(4)  NOT NULL DEFAULT '0' COMMENT '删除标识。0: 未删除, 1: 已删除',
    `gmt_create`         datetime   NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `gmt_modified`       datetime   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_o_id` (`o_id`),
    KEY `idx_order_date` (`order_date`),
    KEY `idx_modified_begin` (`modified_begin`),
    KEY `idx_gmt_modified` (`gmt_modified`)
) ENGINE = InnoDB COMMENT ='订单查询接口';
